---
version: '3.2'
services:
  syncthing:
    image: derektamsen/syncthing
    build: ./
    read_only: true
    restart: on-failure:5
    volumes:
      - data:/data
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
volumes:
  data:
    driver: local
