---
version: '3.2'
services:
  syncthing:
    image: quay.io/derektamsen/docker-syncthing
    build: ./
    read_only: true
    restart: on-failure:5
    volumes:
      - data-nfs:/data
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
volumes:
  data-nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},nolock,soft,rw"
      device: ":${NFS_VOLUME_DATA}"
