#!/usr/bin/env bash

DATADIR='/data'

echo 'Creating datadir...'
sudo mkdir -p "${DATADIR}"

echo 'Starting the data container...'
sudo docker run --memory 512m --cpu-shares 512 -v "${DATADIR}/syncthing":/data \
  --read-only --name syncthing-data derektamsen/syncthing-data

echo 'Starting the service container...'
sudo docker run -d --restart on-failure:5 --net host --memory 512m --cpu-shares 512 \
  --read-only --volumes-from syncthing-data --name syncthing derektamsen/syncthing
