#!/usr/bin/env bash

echo 'Starting the data container...'
sudo docker run -v /data/syncthing:/data --name syncthing-data derektamsen/syncthing-data

echo 'Starting the service container...'
sudo docker run -d --restart always --net host --volumes-from syncthing-data \
  --name syncthing derektamsen/syncthing
